import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/layout/Navbar'
import ReactQueryProvider from '@/components/provider/ReactQueryProvider'
import ThemeProvider from '@/components/provider/ThemeProvider'
import { Nunito } from 'next/font/google'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const font = Nunito({
    subsets: ['latin'],
})

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cn('flex h-screen flex-col', font.className)}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    <ReactQueryProvider>
                        <Navbar />
                        {children}
                    </ReactQueryProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}
